### ISSUE TITLE
Research exsisting bots

### ISSUE THREAD

**Issue by FabianKongelf** [vortexntnu/github-iac#1]

**Comment by FabianKongelf** [comment]
Find out if there exists a bot for manipulating GitHub actions or manage / send files to GitHub repositories. Use max 3 hours on this research.

**Comment by nilsloe** [comment]
I have not been able to find a bot to automate github actions. Github subtree or github submodules might be possible to use for different repositories that rely on another specific repository, although they both have demerits.
