### ISSUE TITLE
Outline bot requirements

### ISSUE THREAD

**Issue by FabianKongelf** [vortexntnu/github-iac#4]
If found a bot to solve task or based on knowledge on probing GitHub endpoints, what information do a bot need to complete it's task, for instance do it need a repository id and/or a access token?

**Comment by FabianKongelf** [comment]
Start by outline the overall goals and purpose of a github manager bot

**Comment by EirikKolas** [comment]
# Want bot to manage workflows
- Central place to host workflows
- Bot to update workflows to the repos that use those workflows

## More specific
- One location for workflows
- When we push to this location, it will update all other instances of the code.
